trigger:
  branches:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'

variables:
  MainProject: $(Build.SourcesDirectory)/src/IxMilia.Lisp/IxMilia.Lisp.csproj

stages:
- stage: Build
  jobs:
  - job: Windows
    pool:
      vmImage: windows-2019
    strategy:
      maxParallel: 2
      matrix:
        debug:
          _configuration: Debug
        release:
          _configuration: Release
    steps:
    - checkout: self
      clean: true
    - script: build-and-test.cmd -c $(_configuration)
      displayName: Build / Test
    - script: 'dotnet pack --no-restore --no-build -c $(_configuration) -o "$(Build.ArtifactStagingDirectory)" "$(MainProject)"'
      displayName: Pack
    - task: PublishBuildArtifacts@1
      displayName: Publish Package
      condition: and(succeeded(), eq(variables['_configuration'], 'Release'))
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)
        artifactName: packages
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    strategy:
      maxParallel: 2
      matrix:
        debug:
          _configuration: Debug
        release:
          _configuration: Release
    steps:
    - checkout: self
      clean: true
    - script: ./build-and-test.sh -c $(_configuration)
      displayName: Build / Test
    - script: 'dotnet pack --no-restore --no-build -c $(_configuration) -o "$(Build.ArtifactStagingDirectory)" "$(MainProject)"'
      displayName: Pack
